# Generated by Django 3.1.2 on 2020-12-23 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hexes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hexNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('players', models.ManyToManyField(to='App.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Economic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.CharField(max_length=100)),
                ('factory_num', models.IntegerField()),
                ('resentment', models.DecimalField(decimal_places=50, max_digits=70)),
                ('steel_prod', models.DecimalField(decimal_places=50, max_digits=70)),
                ('oil_prod', models.DecimalField(decimal_places=50, max_digits=70)),
                ('welfare', models.DecimalField(decimal_places=50, max_digits=70)),
                ('population', models.DecimalField(decimal_places=50, max_digits=70)),
                ('hexnum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.hexes')),
                ('player_controller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.player')),
            ],
        ),
    ]
