# Generated by Django 3.1.2 on 2020-12-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20201225_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.game'),
        ),
    ]
