# Generated by Django 3.1.2 on 2020-12-27 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_player_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.game'),
        ),
        migrations.AlterField(
            model_name='indtariff',
            name='tariffAm',
            field=models.DecimalField(decimal_places=50, default=0, max_digits=70),
        ),
    ]
