# Generated by Django 3.1.2 on 2021-01-05 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_player_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexes',
            name='capital',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hexes',
            name='coal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hexes',
            name='color',
            field=models.CharField(default='#ffffff', max_length=50),
        ),
        migrations.AddField(
            model_name='hexes',
            name='controller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hexes',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hexes',
            name='iron',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hexes',
            name='oil',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hexes',
            name='population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hexes',
            name='wheat',
            field=models.IntegerField(default=0),
        ),
    ]
