# Generated by Django 3.1.2 on 2021-01-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20210105_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.CharField(default='#ffffff', max_length=50),
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('naval', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.game')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.hexes')),
            ],
        ),
    ]
