# Generated by Django 3.1.2 on 2021-01-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20210106_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='moved',
            field=models.BooleanField(default=False),
        ),
    ]
