# Generated by Django 3.1.2 on 2021-01-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20210109_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexes',
            name='xLocation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hexes',
            name='yLocation',
            field=models.IntegerField(default=0),
        ),
    ]
