# Generated by Django 3.1.2 on 2021-01-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20210109_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='max_movement',
            field=models.IntegerField(default=1),
        ),
    ]
