# Generated by Django 3.1.2 on 2021-01-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20210113_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Bonds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='CorporateTax',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=5),
        ),
        migrations.AddField(
            model_name='player',
            name='Education',
            field=models.DecimalField(decimal_places=4, default=0.3, max_digits=5),
        ),
        migrations.AddField(
            model_name='player',
            name='IncomeTax',
            field=models.DecimalField(decimal_places=4, default=0.2, max_digits=5),
        ),
        migrations.AddField(
            model_name='player',
            name='Military',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='player',
            name='MoneyPrinting',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='player',
            name='Welfare',
            field=models.DecimalField(decimal_places=4, default=0.7, max_digits=5),
        ),
    ]
