# Generated by Django 3.1.2 on 2021-01-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20210113_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Bonds',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='CorporateTax',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='player',
            name='Education',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='player',
            name='IncomeTax',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='player',
            name='Military',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='Welfare',
            field=models.FloatField(default=0.7),
        ),
    ]
