# Generated by Django 3.1.2 on 2021-01-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_player_goodspercapita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='GoodsPerCapita',
            field=models.ImageField(default='default_graph', upload_to='graphs'),
        ),
    ]
