# Generated by Django 3.1.2 on 2021-01-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20210113_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Employment',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='player',
            name='Inflation',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='player',
            name='RealGDP',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
    ]
