# Generated by Django 3.1.2 on 2021-01-16 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_auto_20210114_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.player')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=50)),
                ('applied', models.BooleanField(default=False)),
                ('SavingsEffect', models.FloatField(default=0)),
                ('ConsumptionEffect', models.FloatField(default=0)),
                ('WelfareEffect', models.FloatField(default=0)),
                ('InequalityEffect', models.FloatField(default=0)),
                ('HealthSpend', models.FloatField(default=0)),
                ('Healthcare', models.IntegerField(default=0)),
                ('ConsumerLoans', models.FloatField(default=0)),
                ('Education', models.FloatField(default=0)),
                ('GovGoods', models.FloatField(default=0)),
                ('WageEffect', models.FloatField(default=0)),
                ('PopEffect', models.FloatField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.player')),
                ('policy_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.policygroup')),
            ],
        ),
    ]
