# Generated by Django 3.1.2 on 2021-01-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_auto_20210116_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='player',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.player'),
        ),
    ]
