# Generated by Django 3.1.2 on 2021-01-18 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_auto_20210116_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexes',
            name='start_country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.country'),
        ),
    ]
