# Generated by Django 3.1.2 on 2021-01-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_hexes_start_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexes',
            name='center',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indtariff',
            name='tariffAm',
            field=models.FloatField(default=0),
        ),
    ]
