# Generated by Django 3.1.2 on 2021-01-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_auto_20210118_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(default=4),
        ),
    ]
