# Generated by Django 3.1.2 on 2021-01-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_game_num_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='curr_num_players',
            field=models.IntegerField(default=0),
        ),
    ]
