# Generated by Django 3.1.2 on 2021-01-21 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_game_curr_num_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=50)),
                ('controller', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.game')),
            ],
        ),
        migrations.CreateModel(
            name='Pops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationLevel', models.IntegerField(default=0)),
                ('Income', models.FloatField(default=0)),
                ('Occupation', models.CharField(default='Unemployed', max_length=50)),
                ('Population_size', models.IntegerField(default=0)),
                ('trust', models.IntegerField(default=100)),
                ('Faction', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.faction')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.game')),
            ],
        ),
        migrations.CreateModel(
            name='PolicySupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faction', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.faction')),
                ('PolicyAssociated', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.policy')),
                ('controller', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.game')),
            ],
        ),
    ]
