# Generated by Django 3.1.2 on 2021-01-27 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_faction_policysupport_pops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indtariff',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.player'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='curr_player',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.player'),
        ),
    ]
