# Generated by Django 3.1.2 on 2021-01-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_auto_20210127_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='color',
            field=models.CharField(default='#ffffff', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='color',
            field=models.CharField(default='#ffffff', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(default=5),
        ),
    ]
