# Generated by Django 3.1.2 on 2021-01-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_auto_20210127_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Capital',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='player',
            name='GDP',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='player',
            name='GDPGrowth',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='player',
            name='GDPPerCapita',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='player',
            name='GoodsProduction',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='player',
            name='GovBudget',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='player',
            name='InterestRate',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='player',
            name='tradeBalance',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
    ]
