# Generated by Django 3.1.2 on 2021-03-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_auto_20210127_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='AppliedInvest',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='player',
            name='InfrastructureInvest',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='PracticalInvest',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='player',
            name='ScienceInvest',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='TheoreticalInvest',
            field=models.FloatField(default=0.1),
        ),
    ]
