# Generated by Django 3.1.2 on 2021-03-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_auto_20210322_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='AdditionalWelfare',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='player',
            name='Welfare',
            field=models.FloatField(default=0.0),
        ),
    ]
