# Generated by Django 3.1.2 on 2021-11-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_auto_20210322_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Consumption',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='game',
            name='Employment',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='game',
            name='GoodsBalance',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='game',
            name='GoodsPerCapita',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='game',
            name='Inflation',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='game',
            name='InterestRate',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='game',
            name='Resentment',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AlterField(
            model_name='army',
            name='max_movement',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='InfrastructureInvest',
            field=models.FloatField(default=0.1),
        ),
    ]
