# Generated by Django 3.1.2 on 2021-11-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_auto_20211114_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='indtariff',
            name='sanctionAm',
            field=models.FloatField(default=0),
        ),
    ]
