# Generated by Django 3.1.2 on 2021-12-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_indtariff_sanctionam'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ScienceArr',
            field=models.ImageField(default='default_graph.png', upload_to='graphs'),
        ),
        migrations.AlterField(
            model_name='player',
            name='AdditionalWelfare',
            field=models.FloatField(default=0.6),
        ),
    ]
