# Generated by Django 3.1.2 on 2022-01-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_auto_20220115_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exportRestriction',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='subsidy',
            field=models.FloatField(default=0.125),
        ),
    ]
