# Generated by Django 3.1.2 on 2022-01-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_auto_20220115_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='AdditionalWelfare',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='player',
            name='Education',
            field=models.FloatField(default=0.06),
        ),
        migrations.AlterField(
            model_name='player',
            name='InfrastructureInvest',
            field=models.FloatField(default=0.02),
        ),
    ]
