# Generated by Django 3.1.2 on 2022-01-20 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_auto_20220115_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Education',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='player',
            name='InfrastructureInvest',
            field=models.FloatField(default=0.017),
        ),
        migrations.AlterField(
            model_name='player',
            name='Military',
            field=models.FloatField(default=0.01),
        ),
        migrations.CreateModel(
            name='MapInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('PO', 'Political'), ('RE', 'Resources')], default='PO', max_length=2)),
                ('controller', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.game')),
            ],
        ),
    ]
