# Generated by Django 3.1.2 on 2022-01-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_auto_20220120_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='indtariff',
            name='nationalization',
            field=models.FloatField(default=0),
        ),
    ]
