# Generated by Django 3.1.2 on 2022-02-20 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0044_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('IT', 'Income Tax'), ('CT', 'Corporate Tax'), ('WE', 'Welfare'), ('ED', 'Education'), ('SI', 'Science'), ('II', 'Infrastructure Spending'), ('MS', 'Military Spending'), ('MP', 'MoneyPrinting')], default='IT', max_length=2)),
                ('controller', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.game')),
            ],
        ),
    ]
