# Generated by Django 3.1.2 on 2022-02-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_graphinterface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphinterface',
            name='mode',
            field=models.CharField(choices=[('Income_Tax', 'Income Tax'), ('Corporate_Tax', 'Corporate Tax'), ('Welfare', 'Welfare'), ('Education', 'Education'), ('Science', 'Science'), ('Infrastructure', 'Infrastructure Spending'), ('Military', 'Military Spending'), ('MoneyPrintingArr', 'Money Printing')], default='Income_Tax', max_length=20),
        ),
    ]
