# Generated by Django 3.1.2 on 2022-03-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0047_auto_20220221_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphCountryInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.player')),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.country')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.game')),
            ],
        ),
    ]
