# Generated by Django 3.1.2 on 2022-03-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0048_graphcountryinterface'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='neutral',
            field=models.CharField(default='', max_length=100),
        ),
    ]
