# Generated by Django 3.1.2 on 2022-03-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0049_game_neutral'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_size',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='game',
            name='neutral',
            field=models.CharField(default='Neutral', max_length=100),
        ),
        migrations.AlterField(
            model_name='indtariff',
            name='tariffAm',
            field=models.FloatField(default=0.1),
        ),
    ]
