# Generated by Django 3.1.2 on 2022-03-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0050_auto_20220313_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='robot',
            field=models.BooleanField(default=False),
        ),
    ]
