# Generated by Django 3.1.2 on 2022-03-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0051_player_robot'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='large',
            field=models.BooleanField(default=False),
        ),
    ]
