# Generated by Django 3.1.2 on 2022-03-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0052_country_large'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphcountryinterface',
            name='large',
            field=models.BooleanField(default=False),
        ),
    ]
