# Generated by Django 3.1.2 on 2022-03-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0053_graphcountryinterface_large'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
