# Generated by Django 3.1.2 on 2022-08-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0056_player_projection_unloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
