# Generated by Django 3.1.2 on 2022-08-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0057_auto_20220825_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='MilitaryAm',
            field=models.IntegerField(default=0),
        ),
    ]
