# Generated by Django 3.1.2 on 2022-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0058_player_militaryam'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='iron',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='oil',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wheat',
            field=models.IntegerField(default=0),
        ),
    ]
