# Generated by Django 3.1.2 on 2022-08-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0059_auto_20220825_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('building_type', models.CharField(choices=[('CoalMine', 'Coal Mine'), ('IronMine', 'Iron Mine'), ('OilWell', 'Oil Well'), ('Farm', 'Farm'), ('Science', 'Science'), ('Infrastructure', 'Road'), ('Military', 'Recruitment Center'), ('Commercial', 'Commercial')], default='Farm', max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.game')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.hexes')),
                ('player_controller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.player')),
            ],
        ),
    ]
