# Generated by Django 3.1.2 on 2022-08-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0061_remove_building_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.hexes'),
        ),
        migrations.AlterField(
            model_name='building',
            name='player_controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.player'),
        ),
    ]
