# Generated by Django 4.1.2 on 2022-10-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0064_auto_20220913_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ammunition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='metal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='sugar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wood',
            field=models.IntegerField(default=0),
        ),
    ]
