# Generated by Django 4.1.1 on 2022-10-27 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0064_auto_20220913_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_health', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('movement', models.IntegerField(default=0)),
                ('troop_count', models.IntegerField(default=0)),
                ('troop_capacity', models.IntegerField(default=0)),
                ('cool_down', models.IntegerField(default=0)),
                ('reload_speed', models.FloatField(default=1.0)),
                ('range_attack', models.FloatField(default=1.0)),
                ('range_visibility', models.FloatField(default=1.0)),
                ('ship_type', models.CharField(choices=[('Merchant Ship', 'Merchant Ship'), ('Colonizer', 'Colonizer'), ('Small Warship', 'Small Warship'), ('Medium Warship', 'Medium Warship'), ('Big Warship', 'Big Warship')], default='Merchant Ship', max_length=20)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.game')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.hexes')),
            ],
        ),
    ]
