# Generated by Django 4.1.2 on 2022-10-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0065_player_ammunition_player_food_player_gold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexes',
            name='ammunition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hexes',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hexes',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hexes',
            name='metal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hexes',
            name='sugar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hexes',
            name='wood',
            field=models.IntegerField(default=0),
        ),
    ]
