# Generated by Django 3.1.2 on 2022-10-27 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0066_hexes_ammunition_hexes_food_hexes_gold_hexes_metal_and_more'),
        ('App', '0065_ship'),
    ]

    operations = [
    ]
