# Generated by Django 4.1.2 on 2022-11-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0067_game_gameend_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
