# Generated by Django 4.1.2 on 2022-11-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0068_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='NationsDefeated',
            field=models.IntegerField(default=0),
        ),
    ]
