# Generated by Django 3.1.2 on 2022-11-17 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0069_player_nationsdefeated'),
        ('App', '0067_merge_20221027_0233'),
    ]

    operations = [
    ]
