# Generated by Django 3.1.2 on 2022-11-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0070_merge_20221117_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('City', 'City'), ('Factory', 'Factory'), ('Farm', 'Farm'), ('Mine', 'Mine'), ("Woodcutter's Lodge", "Woodcutter's Lodge"), ('Port', 'Port')], default='Farm', max_length=20),
        ),
        migrations.AlterField(
            model_name='ship',
            name='ship_type',
            field=models.CharField(choices=[('Merchant Ship', 'Merchant Ship'), ('Colonizer Ship', 'Colonizer Ship'), ('Doctor Ship', 'Doctor Ship'), ('TugBoat Ship', 'TugBoat Ship'), ('Small Warship', 'Small Warship'), ('Medium Warship', 'Medium Warship'), ('Big Warship', 'Big Warship')], default='Small Warship', max_length=20),
        ),
    ]
